name: Test workflow

# Trigger the workflow on pull requests
on:
  pull_requests:
    branches:
      - develop

# Jobs to run
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm run test